-- Turkish Language Assessment - Supabase schema
-- DKT login + coded participants + age forms + sessions + scored responses
-- No audio analysis and no AI.

create extension if not exists pgcrypto;

do $$
begin
  if not exists (select 1 from pg_type where typname = 'tsa_role') then
    create type public.tsa_role as enum ('admin', 'researcher', 'dkt');
  end if;
end $$;

create table if not exists public.app_users (
  user_id uuid primary key references auth.users(id) on delete cascade,
  role public.tsa_role not null default 'dkt',
  display_name text,
  created_at timestamptz not null default now()
);

create table if not exists public.participants (
  id uuid primary key default gen_random_uuid(),
  code text not null unique,
  created_by uuid not null references auth.users(id),
  created_at timestamptz not null default now(),
  constraint participant_code_format check (code ~ '^[A-Z0-9_-]{2,20}$')
);

create table if not exists public.test_sessions (
  id uuid primary key default gen_random_uuid(),
  participant_id uuid not null references public.participants(id) on delete cascade,
  created_by uuid not null references auth.users(id),
  status text not null default 'in_progress'
    check (status in ('in_progress', 'completed', 'cancelled')),
  assessment_form text,
  started_at timestamptz not null default now(),
  completed_at timestamptz
);

create table if not exists public.responses (
  id bigint generated by default as identity primary key,
  session_id uuid not null references public.test_sessions(id) on delete cascade,
  question_id text not null,
  category text not null,
  selected_option text not null,
  correct_option text not null,
  is_correct boolean not null,
  response_kind text,
  score smallint check (score between 0 and 2),
  max_score smallint check (max_score between 1 and 2),
  replay_count integer not null default 0 check (replay_count >= 0),
  cue_level smallint not null default 0 check (cue_level between 0 and 3),
  assisted_correct boolean not null default false,
  response_time_ms integer check (response_time_ms >= 0),
  answered_at timestamptz not null default now(),
  unique (session_id, question_id)
);

-- Existing projects can safely rerun this file; these statements add the new
-- language-profile fields without changing earlier response records.
alter table public.test_sessions
  add column if not exists assessment_form text;

alter table public.responses
  add column if not exists response_kind text,
  add column if not exists score smallint check (score between 0 and 2),
  add column if not exists max_score smallint check (max_score between 1 and 2),
  add column if not exists replay_count integer not null default 0 check (replay_count >= 0),
  add column if not exists cue_level smallint not null default 0 check (cue_level between 0 and 3),
  add column if not exists assisted_correct boolean not null default false;

create index if not exists idx_participants_created_by
  on public.participants(created_by);

create index if not exists idx_sessions_participant
  on public.test_sessions(participant_id);

create index if not exists idx_sessions_created_by
  on public.test_sessions(created_by);

create index if not exists idx_responses_session
  on public.responses(session_id);

alter table public.app_users enable row level security;
alter table public.participants enable row level security;
alter table public.test_sessions enable row level security;
alter table public.responses enable row level security;

-- Helper predicates are kept inline in policies so the schema stays simple.

drop policy if exists "app_users_self_read" on public.app_users;
create policy "app_users_self_read"
on public.app_users for select
to authenticated
using (user_id = auth.uid());

drop policy if exists "participants_read" on public.participants;
create policy "participants_read"
on public.participants for select
to authenticated
using (
  created_by = auth.uid()
  or exists (
    select 1 from public.app_users u
    where u.user_id = auth.uid()
      and u.role in ('admin', 'researcher')
  )
);

drop policy if exists "participants_insert" on public.participants;
create policy "participants_insert"
on public.participants for insert
to authenticated
with check (created_by = auth.uid());

drop policy if exists "participants_update" on public.participants;
create policy "participants_update"
on public.participants for update
to authenticated
using (
  created_by = auth.uid()
  or exists (
    select 1 from public.app_users u
    where u.user_id = auth.uid()
      and u.role = 'admin'
  )
)
with check (
  created_by = auth.uid()
  or exists (
    select 1 from public.app_users u
    where u.user_id = auth.uid()
      and u.role = 'admin'
  )
);

drop policy if exists "sessions_read" on public.test_sessions;
create policy "sessions_read"
on public.test_sessions for select
to authenticated
using (
  created_by = auth.uid()
  or exists (
    select 1 from public.app_users u
    where u.user_id = auth.uid()
      and u.role in ('admin', 'researcher')
  )
);

drop policy if exists "sessions_insert" on public.test_sessions;
create policy "sessions_insert"
on public.test_sessions for insert
to authenticated
with check (created_by = auth.uid());

drop policy if exists "sessions_update" on public.test_sessions;
create policy "sessions_update"
on public.test_sessions for update
to authenticated
using (
  created_by = auth.uid()
  or exists (
    select 1 from public.app_users u
    where u.user_id = auth.uid()
      and u.role = 'admin'
  )
)
with check (
  created_by = auth.uid()
  or exists (
    select 1 from public.app_users u
    where u.user_id = auth.uid()
      and u.role = 'admin'
  )
);

drop policy if exists "responses_read" on public.responses;
create policy "responses_read"
on public.responses for select
to authenticated
using (
  exists (
    select 1
    from public.test_sessions s
    where s.id = responses.session_id
      and (
        s.created_by = auth.uid()
        or exists (
          select 1 from public.app_users u
          where u.user_id = auth.uid()
            and u.role in ('admin', 'researcher')
        )
      )
  )
);

drop policy if exists "responses_insert" on public.responses;
create policy "responses_insert"
on public.responses for insert
to authenticated
with check (
  exists (
    select 1
    from public.test_sessions s
    where s.id = responses.session_id
      and s.created_by = auth.uid()
  )
);

drop policy if exists "responses_update" on public.responses;
create policy "responses_update"
on public.responses for update
to authenticated
using (
  exists (
    select 1
    from public.test_sessions s
    where s.id = responses.session_id
      and s.created_by = auth.uid()
  )
)
with check (
  exists (
    select 1
    from public.test_sessions s
    where s.id = responses.session_id
      and s.created_by = auth.uid()
  )
);
